### ISSUE TITLE
specify more specific chip for micro:bit v2?

### ISSUE THREAD

**Issue by gcapell** [rust-embedded/discovery#425]
Does a similar thing to #422 need to be applied for micro:bit v2?

**Comment by adamgreig** [comment]
We shouldn't _need_ to, because at the moment there's only one possibility for `nRF52833` (it's `nRF52833_xxAA`), so probe-rs doesn't find any ambiguity and picks it. However, if another nRF52833 variant was added to probe-rs in the future, it would become necessary, so I don't think it would hurt to make the change to `nRF52833_xxAA` now.
